# Project Metadata
name: taza_khabar_app
description: News application built with Flutter
version: 1.0.0+1

# Dart SDK Configuration
environment:
  sdk: '>=3.4.4 <4.0.0'

# Key Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.0     # State management
  dio: ^5.6.0              # HTTP requests
  cached_network_image: ^3.4.1  # Image caching
  intl: ^0.18.0            # Internationalization

# Development Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0   # Code quality checks

# Flutter Configuration
flutter:
  uses-material-design: true
  assets:
    - asset/png/

  # Custom Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf

    - family: Ranade
      fonts:
        - asset: assets/fonts/Ranade/Ranade-Variable.ttf